version: '3'

services:
  mongodb:
    container_name: "mongodb"
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=vozy
      - MONGO_INITDB_ROOT_PASSWORD=1qsw23edfr4
    # App Service
  app:
    # Configuration for building the docker image for the service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    restart: unless-stopped
    depends_on:
      - mongodb